version: "3.8"
services:
  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - RPC_URL=https://fullnode.testnet.sui.io:443
    ports:
      - "8080:8080"

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend